mark unused function with attribute unused
Otherwise

src/tee_socket.c:554:20: error: 'sa_set_port' defined but not used [-Werror=unused-function]
 static TEEC_Result sa_set_port(struct sockaddr *sa, socklen_t slen,

Signed-off-by: Andy Green <andy@warmcat.com>